create database ECOM;	-- CREATING DATABASE ECOM 
USE ECOM;	-- USING DATABASE 

-- CREATING TABLE CUSTOMERS 
create table customers(
CUST_ID varchar(250),
FIRST_NAME VARCHAR(250),
LAST_NAME VARCHAR(250),
EMAIL VARCHAR(250),
GENDER ENUM("Male","Female","Others"),
PHONE VARCHAR(10),
ANNUAL_INCOME decimal(10,2)
); 

select *
FROM CUSTOMERS;