create database ECOM;	-- CREATING DATABASE ECOM 
USE ECOM;	-- USING DATABASE 

-- CREATING TABLE CUSTOMERS 
create table customers(
CUST_ID varchar(250),
FIRST_NAME VARCHAR(250),
LAST_NAME VARCHAR(250),
EMAIL VARCHAR(250),
GENDER ENUM("Male","Female","Others"),
PHONE VARCHAR(10),
ANNUAL_INCOME decimal(10,2)
); 

select *
FROM CUSTOMERS;
DESCRIBE CUSTOMERS;

-- CREATE TABLE OF PRODUCTS 
CREATE TABLE PRODUCTS(
PROD_ID INT PRIMARY KEY,
PROD_NAME VARCHAR(255) UNIQUE,
UNIT_PRICE DECIMAL(10,2),
CATEGORY VARCHAR(255)
);


ALTER TABLE CUSTOMERS 
MODIFY COLUMN CUST_ID VARCHAR(250) PRIMARY KEY;

DESCRIBE CUSTOMERS;
DESCRIBE PRODUCTS;

-- CREAT THE TABLE OF SALES 
CREATE TABLE SALES(
QUANTITY INT,
SALES DECIMAL(10,2),
CUST_ID VARCHAR(255),
PROD_ID INT,
DISCOUNT DECIMAL(3,2),
LOCATION CHAR(50),
ORDER_DATE DATE,
DELIVERY_DATE DATE,
PROFIT DECIMAL(9,2)
);

ALTER TABLE SALES
ADD CONSTRAINT FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID),
ADD CONSTRAINT FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS(PROD_ID);

DESCRIBE SALES;

-- INSERTED VALUES INTO CUSTOMERS TABLE 
INSERT INTO CUSTOMERS(CUST_ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,PHONE,ANNUAL_INCOME) VALUES
("CUST-101","JAY","SAVANE","SAVANEJAY@GMAIL.COM","Male",9685498745,45845),
("CUST-102","HAMILTON",NULL,"HAMILTON@GMAIL.COM","Male",9685125478,45856),
("CUST-103","MAX","VERSTAPEN","SIMPLYLOVLEY@GMAIL.COM","Male",8596478459,NULL),
("CUST-104","GEORGE","RUSSEL",NULL,"Male",8696541254,84596),
("CUST-105","KIMI","ANTONELLI","KIMIANTO@GMAIL.COM","Male",8759685741,48596);


SELECT * FROM CUSTOMERS

